### ISSUE TITLE
A small mistake in camera.py

### ISSUE THREAD

**Issue by cancan233** [bsavery/ray-tracing-one-weekend-taichi#2]
Thanks for your sharing these codes! 

However, I think there might be a small mistake in the camera.py. 

https://github.com/bsavery/ray-tracing-one-weekend-taichi/blob/48f887a49eb03f34a66a611d0717ab11ec0606f9/camera.py#L30

It should be `offset = self.u * rd.x + self.v * rd.y`. Here, `self.u` and `self.v` are from `u`, `v` in `__ini__()` 

Please let me know if you have any questions!

**Comment by bsavery** [comment]
https://github.com/bsavery/ray-tracing-one-weekend-taichi/commit/4584c2972f7a003c8a3983d3d1d8e341d15d17a3 thanks for catching!
